# This file was generated by GoReleaser. DO NOT EDIT.
class Cipherbin < Formula
  desc "CLI tool for communicating with cipherbin to interact with messages"
  homepage ""
  version "0.4.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bradford-hamilton/cipher-bin-cli/releases/download/v0.4.1/cipher-bin-cli_0.4.1_Darwin_x86_64.tar.gz"
    sha256 "93bd2613e61f35720441d4cadb54d0194205d109f0618ad6d48c95b739497416"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bradford-hamilton/cipher-bin-cli/releases/download/v0.4.1/cipher-bin-cli_0.4.1_Linux_x86_64.tar.gz"
      sha256 "aa2ffce1a97d9227d2e9dc2ad2587a6d65d144a41d7c6326de4beff07c1847fe"
    end
  end
  
  depends_on "git"
  depends_on "zsh"

  def install
    bin.install "cipherbin"
  end
end
