# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cipherbin < Formula
  desc "CLI tool for communicating with cipherbin to interact with messages"
  homepage ""
  version "0.6.0"

  depends_on "git"
  depends_on "zsh"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cipherbin/cipher-bin-cli/releases/download/v0.6.0/cipher-bin-cli_0.6.0_darwin_arm64.tar.gz"
      sha256 "8008157373b85efabe08f560810ba9b36fa79c6dc8ee0a79963994bacb7bdfad"

      def install
        bin.install "cipherbin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cipherbin/cipher-bin-cli/releases/download/v0.6.0/cipher-bin-cli_0.6.0_darwin_amd64.tar.gz"
      sha256 "b74984ce8c7f55f5e62bd5d661c22fffb8d381a968b5b4571d53b8511e65421a"

      def install
        bin.install "cipherbin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/cipherbin/cipher-bin-cli/releases/download/v0.6.0/cipher-bin-cli_0.6.0_linux_armv6.tar.gz"
      sha256 "5d57c5438031057e654a53a62386c925e27eb325d220738272746388242f953c"

      def install
        bin.install "cipherbin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cipherbin/cipher-bin-cli/releases/download/v0.6.0/cipher-bin-cli_0.6.0_linux_arm64.tar.gz"
      sha256 "937a68be7beb1c6735dfc0dbec3384f5f32e9d237056974a33c9a756c644d127"

      def install
        bin.install "cipherbin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cipherbin/cipher-bin-cli/releases/download/v0.6.0/cipher-bin-cli_0.6.0_linux_amd64.tar.gz"
      sha256 "97b0ba4d0b1fbff6580f9978a40f257ff7eda5e38623e2081af53b0e5ee080c8"

      def install
        bin.install "cipherbin"
      end
    end
  end
end
